### ISSUE TITLE
English Version?

### ISSUE THREAD

**Issue by DonaldTsang** [daigakulounge/ochinchingadaiskinandayo#1]
Since https://djtguide.neocities.org/ and https://itazuraneko.neocities.org/ do not cover everything in their cornucopia, is is possible for you to translate this resource list into English for comparison?

**Comment by daigakulounge** [comment]
doen and doen

**Comment by DonaldTsang** [comment]
Thanks https://github.com/daigakulounge/ochinchingadaiskinandayo/blob/master/README_EN.md
